export const BACK_END_SERVER ="http://localhost:5000"
export const SIGN_IN_API = "http://localhost:5000/api/account/login"
export const SIGN_UP_API = "http://localhost:5000/api/account/register"
export const GET_PAGE_USERS = "http://localhost:5000/api/admin/list/page"
export const ACCOUNT_API = "http://localhost:5000/api/account"
export const ACCOUNT_GOOGLE_API = "http://localhost:5000/api/account/google"
export const ORDERS_API = "http://localhost:5000/api/order"
export const TRANSACTION_API = "http://localhost:5000/api/transaction"
