export const BACK_END_SERVER ="https://eshop-main-ba453b903e8c.herokuapp.com"
export const SIGN_IN_API = "https://eshop-main-ba453b903e8c.herokuapp.com/api/account/login"
export const SIGN_UP_API = "https://eshop-main-ba453b903e8c.herokuapp.com/account/register"
export const GET_PAGE_USERS = "https://eshop-main-ba453b903e8c.herokuapp.com/api/admin/list/page"
export const ACCOUNT_API = "https://eshop-main-ba453b903e8c.herokuapp.com/api/account"
export const ACCOUNT_GOOGLE_API = "https://eshop-main-ba453b903e8c.herokuapp.com/api/account/google"
export const ORDERS_API = "https://eshop-main-ba453b903e8c.herokuapp.com/api/order"
export const TRANSACTION_API = "https://eshop-main-ba453b903e8c.herokuapp.com/api/trans"
